### ISSUE TITLE
istheutestupa lügt

### ISSUE THREAD

**Issue by glor** [Chrigge/istheutestupa#2]
Heute ist Stupa, aber istheutestupa.de lügt.
Außerdem sollte der Hintergrund grün sein, wenn kein Stupa ist! Und PHP ist widerlich!

**Comment by Chrigge** [comment]
Au weia! Dabei hatte ein netter Mensch doch schon einen Merge request für den Fix hochgeladen :) Ich kümmer mich mal. Außerdem: Au weia, heut ist ja Stupa!

**Comment by Chrigge** [comment]
Geht wieder, eigentlich hatte sich nur der Link zu der Seite mit den Ankündigungen geändert (wegen neuer Legislatur, danke an corvismo!) Das mit dem Grün lasse ich mir noch mal gut durch den Kopf gehen - positive Bestätigung ist nicht grade meine erste Assoziation wenn Stupa ist!

**Comment by glor** [comment]
Nee. so war das nicht gemeint! Grün = kein Stupa; Rot = Stupa!!!
